### ISSUE TITLE
Command /lobby generates spam erros

### ISSUE THREAD

**Issue by gabrielrf01** [kit8379/VelocityBalancer#1]
Im trying to use the /lobby command, im currently receiving the error trace:

Caused by: java.lang.RuntimeException: Unable to invoke command  lobbyfor [connected player] WeyT (/XXXX)
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:258) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$3(VelocityCommandManager.java:292) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more
Caused by: java.lang.StackOverflowError
        at java.base/java.util.stream.SpinedBuffer.asArray(SpinedBuffer.java:214) ~[?:?]
        at java.base/java.util.stream.Nodes$SpinedNodeBuilder.asArray(Nodes.java:1305) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:617) ~[?:?]
        at io.leangen.geantyref.GenericTypeReflector.lambda$merge$18(GenericTypeReflector.java:1148) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
        at java.base/java.util.stream.ReduceOps$2ReducingSink.accept(ReduceOps.java:123) ~[?:?]
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:662) ~[?:?]
        at io.leangen.geantyref.GenericTypeReflector.merge(GenericTypeReflector.java:1147) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
        at io.leangen.geantyref.VarMap.map(VarMap.java:121) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
        at io.leangen.geantyref.GenericTypeReflector.mapTypeParameters(GenericTypeReflector.java:134) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
        at io.leangen.geantyref.GenericTypeReflector.mapTypeParameters(GenericTypeReflector.java:117) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
        at io.leangen.geantyref.GenericTypeReflector.getExactDirectSuperTypes(GenericTypeReflector.java:548) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
        at io.leangen.geantyref.GenericTypeReflector.getExactSuperType(GenericTypeReflector.java:261) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
        at io.leangen.geantyref.GenericTypeReflector.isSuperType(GenericTypeReflector.java:394) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
        at io.leangen.geantyref.TypeFactory.checkParametersWithinBound(TypeFactory.java:209) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
        at io.leangen.geantyref.TypeFactory.parameterizedInnerClass(TypeFactory.java:162) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
        at io.leangen.geantyref.TypeFactory.parameterizedClass(TypeFactory.java:45) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
        at org.spongepowered.configurate.ConfigurationNode.getList(ConfigurationNode.java:705) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
        at org.me.velocitybalancer.velocity.VelocityBalancer.getBalancedServer(VelocityBalancer.java:96) ~[?:?]
        at org.me.velocitybalancer.velocity.VelocityBalancer.getBalancedServer(VelocityBalancer.java:109) ~[?:?]
        at org.me.velocitybalancer.velocity.VelocityBalancer.getBalancedServer(VelocityBalancer.java:109) ~[?:?]
        at org.me.velocitybalancer.velocity.VelocityBalancer.getBalancedServer(VelocityBalancer.java:109) ~[?:?]
        at org.me.velocitybalancer.velocity.VelocityBalancer.getBalancedServer(VelocityBalancer.java:109) ~[?:?]
        at org.me.velocitybalancer.velocity.VelocityBalancer.getBalancedServer(VelocityBalancer.java:109) ~[?:?]

**Comment by Xbani** [comment]
Hi, fixed by removing the two **permission-redirect** from the config.yml
